In [83]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import seaborn as sns
df= pd.read_csv('/Users/marina/Desktop/final_project/data/cleaned/okcupid_preprocessed.csv')
#data/raw/okcupid_profiles .csv

In [84]:
df.head()

,profile_id,age,status,sex,orientation,body_type,diet,drinks,drugs,education,...,my_goals,my_talent,my_highlights,my_favorites,my_needs,think_about,typical_friday,my_secret,message_if,city
0,1000,22,single,m,straight,curvy,anything,sometimes,never,College or more,...,currently working as an international agent fo...,making people laugh. ranting about a good salt...,"the way i look. i am a six foot half asian, ha...","books: absurdistan, the republic, of mice and ...",food. water. cell phone. shelter.,duality and humorous things,trying to find someone to hang out with. i am ...,i am new to california and looking for someone...,you want to be swept off your feet! you are ti...,south san francisco
1,1001,35,single,m,straight,average,other,often,sometimes,College or more,...,dedicating everyday to being an unbelievable b...,being silly. having ridiculous amonts of fun w...,rather not say,i am die hard christopher moore fan. i don't r...,delicious porkness in all of its glories. my b...,rather not say,rather not say,i am very open and will share just about anyth...,rather not say,oakland
2,1002,23,single,m,straight,skinny,vegetarian,sometimes,rather not say,College or more,...,reading things written by old dead people,playing synthesizers and organizing books acco...,socially awkward but i do my best,"bataille, celine, beckett. . . lynch, jarmusch...",rather not say,cats and german philosophy,rather not say,rather not say,you feel so inclined.,berkeley
3,1003,29,single,m,straight,fit,rather not say,sometimes,never,College or more,...,work work work work + play,creating imagery to look at: http://bagsbrown....,i smile a lot and my inquisitive nature,"music: bands, rappers, musicians at the moment...",rather not say,rather not say,rather not say,rather not say,rather not say,san francisco
4,1004,29,single,m,straight,average,anything,sometimes,rather not say,College or more,...,building awesome stuff. figuring out what's im...,imagining random shit. laughing at aforementio...,i have a big smile. i also get asked if i'm we...,"books: to kill a mockingbird, lord of the ring...","like everyone else, i love my friends and fami...",what my contribution to the world is going to ...,out with my friends!,i cried on my first day at school because a bi...,you're awesome.,san francisco

In [85]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47150 entries, 0 to 47149
Data columns (total 32 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   profile_id      47150 non-null  int64
 1   age             47150 non-null  int64
 2   status          47150 non-null  object
 3   sex             47150 non-null  object
 4   orientation     47150 non-null  object
 5   body_type       47150 non-null  object
 6   diet            47150 non-null  object
 7   drinks          47150 non-null  object
 8   drugs           47150 non-null  object
 9   education       47150 non-null  object
 10  ethnicity       47150 non-null  object
 11  height          47150 non-null  float64
 12  income          47150 non-null  int64
 13  job             47150 non-null  object
 14  last_online     47150 non-null  object
 15  offspring       47150 non-null  object
 16  pets            47150 non-null  object
 17  religion        47150 non-null  object
 18  sign            47150 non-null  object
 19  smokes          47150 non-null  object
 20  speaks          47150 non-null  int64
 21  about_me        47150 non-null  object
 22  my_goals        47150 non-null  object
 23  my_talent       47150 non-null  object
 24  my_highlights   47150 non-null  object
 25  my_favorites    47150 non-null  object
 26  my_needs        47150 non-null  object
 27  think_about     47150 non-null  object
 28  typical_friday  47150 non-null  object
 29  my_secret       47150 non-null  object
 30  message_if      47150 non-null  object
 31  city            47150 non-null  object
dtypes: float64(1), int64(4), object(27)
memory usage: 11.5+ MB

In [ ]:
#job,location

# Job

In [86]:
df['job'].unique()

array(['transportation', 'hospitality', 'student', 'arts', 'it',
       'finance', 'marketing', 'other', 'healthcare', 'media',
       'science and tech', 'management', 'education', 'admin',
       'construction', 'politics', 'legal', 'unemployed', 'military',
       'retired'], dtype=object)

In [78]:
df['about_me'].unique()

array(["about me:  i would love to think that i was some some kind of intellectual: either the dumbest smart guy, or the smartest dumb guy. can't say i can tell the difference. i love to talk about ideas and concepts. i forge odd metaphors instead of reciting cliches. like the simularities between a friend of mine's house and an underwater salt mine. my favorite word is salt by the way (weird choice i know). to me most things in life are better as metaphors. i seek to make myself a little better everyday, in some productively lazy way. got tired of tying my shoes. considered hiring a five year old, but would probably have to tie both of our shoes... decided to only wear leather shoes dress shoes.  about you:  you love to have really serious, really deep conversations about really silly stuff. you have to be willing to snap me out of a light hearted rant with a kiss. you don't have to be funny, but you have to be able to make me laugh. you should be able to bend spoons with your mind, and telepathically make me smile while i am still at work. you should love life, and be cool with just letting the wind blow. extra points for reading all this and guessing my favorite video game (no hints given yet). and lastly you have a good attention span.",
       "i am a chef: this is what that means. 1. i am a workaholic. 2. i love to cook regardless of whether i am at work. 3. i love to drink and eat foods that are probably really bad for me. 4. i love being around people that resemble line 1-3. i love the outdoors and i am an avid skier. if its snowing i will be in tahoe at the very least. i am a very confident and friendly. i'm not interested in acting or being a typical guy. i have no time or patience for rediculous acts of territorial pissing. overall i am a very likable easygoing individual. i am very adventurous and always looking forward to doing new things and hopefully sharing it with the right person.",
       'i work in a library and go to school. . .', ...,
       'hello! i enjoy traveling, watching movies, and hanging out with friends. my #1 rule for traveling is to go to places where where i can drink the tap water. =p i\'ve been to japan, washington dc, new york, london, paris, china (an exception to rule #1) and many other places. for the year, i haven\'t decided yet. maybe toronto and montreal. my taste in movies (and television) fall into three genres: comedies, action, and drama. it doesn\'t matter if the film is in english or sub-titled (i can\'t stand dubbed), but it has to be well-written. aside from the traveling and movies, i also enjoy broadway shows (4 shows in 5 nights in vegas a couple years ago), bay area sports (except the sharks), online gaming, good food, and keeping up with current events.  my friends would describe me as easy-going, goofy, thoughtful, consistent, honest, and dependable. i can get serious when i have to be. overall, i like to think that i lead my life by doing what is "right".',
       '"all i have in this world are my balls and my integrity and no one can take either away from you" -momma linda (her daughter and i went to the same nursery)  weed and alcohol are my vices...oh, and the company of women',
       'is it odd that having a little "enemy" status with someone, makes them seem more interesting to me?  i\'m an extremely socially-graced outcast. my totally awkward childhood surprisingly yielded to something extroverted, thoughtful and diplomatic. i\'m a nice guy, i love people, i love humanity, and i can get pretty angry about all of the above. if i end up the loudest guy in the room, i\'m never so loud that i cant hear what anyone else is saying.  though i am often inappropriate and desperately unable to pass up a joke, no one has ever punched me. i think too much, and talk to much, but know when to shut the f up.  for the sake of accurate representation, i\'m going to qualify my "average" body type as a bit of muscle and a bit of fat. note: i have recently become an ebook-reading-cardio-addict. now that i can jog and read oversized print at the same time i can\'t stay away from a treadmill. seriously, 4+ books, 60+ minutes 4+ times a week for 6 weeks and counting.'],
      dtype=object)

In [87]:
#Function to count the number of values in each cell of a specific column

def count_values_per_row(cell, delimiter=','):
    if pd.isna(cell):
        return 0
    return len(cell.split(delimiter))

# Apply the function to the 'ethnicity' column
df['ethnicity_count'] = df['ethnicity'].apply(count_values_per_row)

# Show the result
print(df)

       profile_id  age  status sex orientation body_type            diet  \
0            1000   22  single   m    straight     curvy        anything
1            1001   35  single   m    straight   average           other
2            1002   23  single   m    straight    skinny      vegetarian
3            1003   29  single   m    straight       fit  rather not say
4            1004   29  single   m    straight   average        anything
...           ...  ...     ...  ..         ...       ...             ...
47145       48216   32  single   m    bisexual    skinny        anything
47146       48217   24  single   m    straight       fit        anything
47147       48218   42  single   m    straight   average        anything
47148       48219   27  single   m    straight       fit        anything
47149       48220   39  single   m         gay   average  rather not say

          drinks           drugs        education  ...  \
0      sometimes           never  College or more  ...
1          often       sometimes  College or more  ...
2      sometimes  rather not say  College or more  ...
3      sometimes           never  College or more  ...
4      sometimes  rather not say  College or more  ...
...          ...             ...              ...  ...
47145  sometimes  rather not say  College or more  ...
47146      often       sometimes  College or more  ...
47147      never           never  College or more  ...
47148  sometimes           often  College or more  ...
47149  sometimes  rather not say  College or more  ...

                                               my_talent  \
0      making people laugh. ranting about a good salt...
1      being silly. having ridiculous amonts of fun w...
2      playing synthesizers and organizing books acco...
3      creating imagery to look at: http://bagsbrown....
4      imagining random shit. laughing at aforementio...
...                                                  ...
47145  conscientiousness. adding -ness to words that ...
47146  filmmaking, photography, graphic design, web d...
47147  - looking at things objectively - getting thin...
47148                                          listening
47149  i'm a great bullshitter. i don't know what it ...

                                           my_highlights  \
0      the way i look. i am a six foot half asian, ha...
1                                         rather not say
2                      socially awkward but i do my best
3                i smile a lot and my inquisitive nature
4      i have a big smile. i also get asked if i'm we...
...                                                  ...
47145  probably that i have no hair (unless i'm weari...
47146                                dude, i don't know.
47147  i'm quiet until i get used to the environment ...
47148  it used to be the hair until i mowed it off bu...
47149  either that i am funny/sarcastic, or that i am...

                                            my_favorites  \
0      books: absurdistan, the republic, of mice and ...
1      i am die hard christopher moore fan. i don't r...
2      bataille, celine, beckett. . . lynch, jarmusch...
3      music: bands, rappers, musicians at the moment...
4      books: to kill a mockingbird, lord of the ring...
...                                                  ...
47145  i get anxious when people ask about favorites....
47146  movies: hook (the greatest adventure ever!), g...
47147  last book: "game change". movies: bourne serie...
47148  where to begin musically: right now i listen t...
47149  i just read the help by kathryn stockett, sooo...

                                                my_needs  \
0                      food. water. cell phone. shelter.
1      delicious porkness in all of its glories. my b...
2                                         rather not say
3                                         rather not say
4      like everyone else, i love my friends and fami...
...                                                  ...
47145  water. air. food. clothes (if its cold, though...
47146  iphone contact lenses headphones camera tv rem...
47147  - iphone - friends and family - internet - bay...
47148  music, family, friends, a basketball, hoop, so...
47149  1. family & friends & other humans - interacti...

                                             think_about  \
0                            duality and humorous things
1                                         rather not say
2                             cats and german philosophy
3                                         rather not say
4      what my contribution to the world is going to ...
...                                                  ...
47145                                           thinking
47146  i do most of my thinking on the bus to/from wo...
47147           aside from work, how to improve my home.
47148          what can i do to make someone chuckle....
47149  sex, myself, other people, how amazing everyth...

                                          typical_friday  \
0      trying to find someone to hang out with. i am ...
1                                         rather not say
2                                         rather not say
3                                         rather not say
4                                   out with my friends!
...                                                  ...
47145  was in class friday nights this past semester....
47146      bringin' home bacon, or drinking and shakin'!
47147    out enjoying friendly conversation over dinner.
47148  what i would do on any other day. everydays a ...
47149  out at happy hour with my friends, running int...

                                               my_secret  \
0      i am new to california and looking for someone...
1      i am very open and will share just about anyth...
2                                         rather not say
3                                         rather not say
4      i cried on my first day at school because a bi...
...                                                  ...
47145  i wish my sexual preferences were clearer to m...
47146  when i was 18 i got a tattoo of waldo somewher...
47147               please let me think about this more.
47148  i like walking around in other people's house ...
47149  i wish i could cry like holly hunter in broadc...

                                              message_if                 city  \
0      you want to be swept off your feet! you are ti...  south san francisco
1                                         rather not say              oakland
2                                  you feel so inclined.             berkeley
3                                         rather not say        san francisco
4                                        you're awesome.        san francisco
...                                                  ...                  ...
47145              you don't know what it's all about...        san francisco
47146     meh if you made it this far you might as well.        san francisco
47147                         we have similar interests.  south san francisco
47148              you are interested and interesting...        san francisco
47149  if you have a back-bone, an opinion, a sense o...        san francisco

      ethnicity_count
0                   1
1                   1
2                   1
3                   1
4                   1
...               ...
47145               1
47146               1
47147               1
47148               1
47149               1

[47150 rows x 33 columns]

In [88]:
df['ethnicity'].unique()

array(['asian', 'white', 'hispanic', 'rather not say', 'other', 'black',
       'indian'], dtype=object)

In [89]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47150 entries, 0 to 47149
Data columns (total 33 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   profile_id       47150 non-null  int64
 1   age              47150 non-null  int64
 2   status           47150 non-null  object
 3   sex              47150 non-null  object
 4   orientation      47150 non-null  object
 5   body_type        47150 non-null  object
 6   diet             47150 non-null  object
 7   drinks           47150 non-null  object
 8   drugs            47150 non-null  object
 9   education        47150 non-null  object
 10  ethnicity        47150 non-null  object
 11  height           47150 non-null  float64
 12  income           47150 non-null  int64
 13  job              47150 non-null  object
 14  last_online      47150 non-null  object
 15  offspring        47150 non-null  object
 16  pets             47150 non-null  object
 17  religion         47150 non-null  object
 18  sign             47150 non-null  object
 19  smokes           47150 non-null  object
 20  speaks           47150 non-null  int64
 21  about_me         47150 non-null  object
 22  my_goals         47150 non-null  object
 23  my_talent        47150 non-null  object
 24  my_highlights    47150 non-null  object
 25  my_favorites     47150 non-null  object
 26  my_needs         47150 non-null  object
 27  think_about      47150 non-null  object
 28  typical_friday   47150 non-null  object
 29  my_secret        47150 non-null  object
 30  message_if       47150 non-null  object
 31  city             47150 non-null  object
 32  ethnicity_count  47150 non-null  int64
dtypes: float64(1), int64(5), object(27)
memory usage: 11.9+ MB

# about me

In [81]:
#about_ me

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

# Initialize the CountVectorizer
vectorizer = CountVectorizer(stop_words='english', max_features=30)

# Fit and transform the 'about_me' column
X = vectorizer.fit_transform(df['about_me'])

# Convert the result to a DataFrame
keywords_df = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
keywords_df.info()

#travel, family, friends, fun, passionate, laugh, work, love, enjoy, new

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47150 entries, 0 to 47149
Data columns (total 30 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   bay      47150 non-null  int64
 1   don      47150 non-null  int64
 2   enjoy    47150 non-null  int64
 3   friends  47150 non-null  int64
 4   fun      47150 non-null  int64
 5   going    47150 non-null  int64
 6   good     47150 non-null  int64
 7   great    47150 non-null  int64
 8   just     47150 non-null  int64
 9   know     47150 non-null  int64
 10  life     47150 non-null  int64
 11  like     47150 non-null  int64
 12  live     47150 non-null  int64
 13  looking  47150 non-null  int64
 14  love     47150 non-null  int64
 15  make     47150 non-null  int64
 16  music    47150 non-null  int64
 17  new      47150 non-null  int64
 18  people   47150 non-null  int64
 19  person   47150 non-null  int64
 20  pretty   47150 non-null  int64
 21  really   47150 non-null  int64
 22  say      47150 non-null  int64
 23  things   47150 non-null  int64
 24  think    47150 non-null  int64
 25  time     47150 non-null  int64
 26  ve       47150 non-null  int64
 27  want     47150 non-null  int64
 28  work     47150 non-null  int64
 29  years    47150 non-null  int64
dtypes: int64(30)
memory usage: 10.8 MB

# my_goals

In [31]:
#my_goals 

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

# Initialize the CountVectorizer
vectorizer = CountVectorizer(stop_words='english', max_features=20)

# Fit and transform the 'about_me' column
X = vectorizer.fit_transform(df['my_goals'])

# Convert the result to a DataFrame
gkeywords_df = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
gkeywords_df.info()

#life, work, school, work, new, people, job, friends, people, time

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47221 entries, 0 to 47220
Data columns (total 20 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   currently  47221 non-null  int64
 1   day        47221 non-null  int64
 2   doing      47221 non-null  int64
 3   friends    47221 non-null  int64
 4   going      47221 non-null  int64
 5   job        47221 non-null  int64
 6   just       47221 non-null  int64
 7   life       47221 non-null  int64
 8   like       47221 non-null  int64
 9   love       47221 non-null  int64
 10  new        47221 non-null  int64
 11  people     47221 non-null  int64
 12  say        47221 non-null  int64
 13  school     47221 non-null  int64
 14  things     47221 non-null  int64
 15  time       47221 non-null  int64
 16  trying     47221 non-null  int64
 17  ve         47221 non-null  int64
 18  work       47221 non-null  int64
 19  working    47221 non-null  int64
dtypes: int64(20)
memory usage: 7.2 MB

# my talent

In [33]:
#my_goals 

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

# Initialize the CountVectorizer
vectorizer = CountVectorizer(stop_words='english', max_features=30)

# Fit and transform the 'about_me' column
X = vectorizer.fit_transform(df['my_talent'])

# Convert the result to a DataFrame
tkeywords_df = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
tkeywords_df.info()

#life, people, love, cooking, friends, laugh, playing, fun, dancing, listening

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47221 entries, 0 to 47220
Data columns (total 30 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   cooking    47221 non-null  int64
 1   dancing    47221 non-null  int64
 2   finding    47221 non-null  int64
 3   friends    47221 non-null  int64
 4   fun        47221 non-null  int64
 5   getting    47221 non-null  int64
 6   good       47221 non-null  int64
 7   great      47221 non-null  int64
 8   having     47221 non-null  int64
 9   just       47221 non-null  int64
 10  know       47221 non-null  int64
 11  laugh      47221 non-null  int64
 12  laughing   47221 non-null  int64
 13  life       47221 non-null  int64
 14  like       47221 non-null  int64
 15  listening  47221 non-null  int64
 16  love       47221 non-null  int64
 17  make       47221 non-null  int64
 18  making     47221 non-null  int64
 19  new        47221 non-null  int64
 20  people     47221 non-null  int64
 21  playing    47221 non-null  int64
 22  pretty     47221 non-null  int64
 23  really     47221 non-null  int64
 24  say        47221 non-null  int64
 25  things     47221 non-null  int64
 26  think      47221 non-null  int64
 27  time       47221 non-null  int64
 28  ve         47221 non-null  int64
 29  writing    47221 non-null  int64
dtypes: int64(30)
memory usage: 10.8 MB

# my_highlights

In [34]:
#my_highlights

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

# Initialize the CountVectorizer
vectorizer = CountVectorizer(stop_words='english', max_features=30)

# Fit and transform the 'about_me' column
X = vectorizer.fit_transform(df['my_highlights'])

# Convert the result to a DataFrame
hkeywords_df = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
hkeywords_df.info()

# hair, humor, eyes, laugh, smile, tall, personality, people, pretty, height

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47221 entries, 0 to 47220
Data columns (total 30 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   big          47221 non-null  int64
 1   blue         47221 non-null  int64
 2   don          47221 non-null  int64
 3   eyes         47221 non-null  int64
 4   good         47221 non-null  int64
 5   hair         47221 non-null  int64
 6   height       47221 non-null  int64
 7   humor        47221 non-null  int64
 8   just         47221 non-null  int64
 9   know         47221 non-null  int64
 10  laugh        47221 non-null  int64
 11  like         47221 non-null  int64
 12  look         47221 non-null  int64
 13  lot          47221 non-null  int64
 14  maybe        47221 non-null  int64
 15  notice       47221 non-null  int64
 16  people       47221 non-null  int64
 17  personality  47221 non-null  int64
 18  pretty       47221 non-null  int64
 19  probably     47221 non-null  int64
 20  really       47221 non-null  int64
 21  say          47221 non-null  int64
 22  sense        47221 non-null  int64
 23  smile        47221 non-null  int64
 24  tall         47221 non-null  int64
 25  tell         47221 non-null  int64
 26  think        47221 non-null  int64
 27  told         47221 non-null  int64
 28  usually      47221 non-null  int64
 29  ve           47221 non-null  int64
dtypes: int64(30)
memory usage: 10.8 MB

# my_favourites

In [38]:
#my_highlights

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

# Initialize the CountVectorizer
vectorizer = CountVectorizer(stop_words='english', max_features=50)

# Fit and transform the 'about_me' column
X = vectorizer.fit_transform(df['my_favorites'])

# Convert the result to a DataFrame
fkeywords_df = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
fkeywords_df.info()

# books, music, movie, shows, tv, eat, food, read, life, family

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47221 entries, 0 to 47220
Data columns (total 50 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   american   47221 non-null  int64
 1   big        47221 non-null  int64
 2   black      47221 non-null  int64
 3   book       47221 non-null  int64
 4   books      47221 non-null  int64
 5   don        47221 non-null  int64
 6   eat        47221 non-null  int64
 7   enjoy      47221 non-null  int64
 8   family     47221 non-null  int64
 9   favorite   47221 non-null  int64
 10  favorites  47221 non-null  int64
 11  fiction    47221 non-null  int64
 12  food       47221 non-null  int64
 13  good       47221 non-null  int64
 14  great      47221 non-null  int64
 15  house      47221 non-null  int64
 16  indian     47221 non-null  int64
 17  italian    47221 non-null  int64
 18  just       47221 non-null  int64
 19  life       47221 non-null  int64
 20  like       47221 non-null  int64
 21  list       47221 non-null  int64
 22  listen     47221 non-null  int64
 23  ll         47221 non-null  int64
 24  lot        47221 non-null  int64
 25  love       47221 non-null  int64
 26  men        47221 non-null  int64
 27  mexican    47221 non-null  int64
 28  movie      47221 non-null  int64
 29  movies     47221 non-null  int64
 30  music      47221 non-null  int64
 31  new        47221 non-null  int64
 32  old        47221 non-null  int64
 33  pretty     47221 non-null  int64
 34  read       47221 non-null  int64
 35  reading    47221 non-null  int64
 36  really     47221 non-null  int64
 37  rock       47221 non-null  int64
 38  say        47221 non-null  int64
 39  series     47221 non-null  int64
 40  shows      47221 non-null  int64
 41  stuff      47221 non-null  int64
 42  sushi      47221 non-null  int64
 43  thai       47221 non-null  int64
 44  things     47221 non-null  int64
 45  time       47221 non-null  int64
 46  tv         47221 non-null  int64
 47  ve         47221 non-null  int64
 48  watch      47221 non-null  int64
 49  world      47221 non-null  int64
dtypes: int64(50)
memory usage: 18.0 MB

#  my needs

In [40]:
#my_highlights

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

# Initialize the CountVectorizer
vectorizer = CountVectorizer(stop_words='english', max_features=20)

# Fit and transform the 'about_me' column
X = vectorizer.fit_transform(df['my_needs'])

# Convert the result to a DataFrame
nkeywords_df = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
nkeywords_df.info()

# books, music, internet, coffee, friends , laughter, phone, family, love, food

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47221 entries, 0 to 47220
Data columns (total 20 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   books     47221 non-null  int64
 1   coffee    47221 non-null  int64
 2   computer  47221 non-null  int64
 3   family    47221 non-null  int64
 4   food      47221 non-null  int64
 5   friends   47221 non-null  int64
 6   good      47221 non-null  int64
 7   internet  47221 non-null  int64
 8   iphone    47221 non-null  int64
 9   laughter  47221 non-null  int64
 10  life      47221 non-null  int64
 11  like      47221 non-null  int64
 12  love      47221 non-null  int64
 13  music     47221 non-null  int64
 14  people    47221 non-null  int64
 15  phone     47221 non-null  int64
 16  say       47221 non-null  int64
 17  things    47221 non-null  int64
 18  time      47221 non-null  int64
 19  water     47221 non-null  int64
dtypes: int64(20)
memory usage: 7.2 MB

# think about

In [42]:
#my_highlights

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

# Initialize the CountVectorizer
vectorizer = CountVectorizer(stop_words='english', max_features=30)

# Fit and transform the 'about_me' column
X = vectorizer.fit_transform(df['think_about'])

# Convert the result to a DataFrame
takeywords_df = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
takeywords_df.info()

# friends, future, work, love, people, time, travel, world, music, family

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47221 entries, 0 to 47220
Data columns (total 30 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   better    47221 non-null  int64
 1   day       47221 non-null  int64
 2   doing     47221 non-null  int64
 3   don       47221 non-null  int64
 4   family    47221 non-null  int64
 5   friends   47221 non-null  int64
 6   future    47221 non-null  int64
 7   going     47221 non-null  int64
 8   good      47221 non-null  int64
 9   just      47221 non-null  int64
 10  life      47221 non-null  int64
 11  like      47221 non-null  int64
 12  lot       47221 non-null  int64
 13  love      47221 non-null  int64
 14  make      47221 non-null  int64
 15  music     47221 non-null  int64
 16  new       47221 non-null  int64
 17  people    47221 non-null  int64
 18  really    47221 non-null  int64
 19  say       47221 non-null  int64
 20  spend     47221 non-null  int64
 21  things    47221 non-null  int64
 22  think     47221 non-null  int64
 23  thinking  47221 non-null  int64
 24  time      47221 non-null  int64
 25  travel    47221 non-null  int64
 26  want      47221 non-null  int64
 27  way       47221 non-null  int64
 28  work      47221 non-null  int64
 29  world     47221 non-null  int64
dtypes: int64(30)
memory usage: 10.8 MB

# typical friday

In [46]:
#my_highlights

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

# Initialize the CountVectorizer
vectorizer = CountVectorizer(stop_words='english', max_features=30)

# Fit and transform the 'about_me' column
X = vectorizer.fit_transform(df['typical_friday'])

# Convert the result to a DataFrame
tykeywords_df = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
tykeywords_df.info()

# movie, work, bar, dancing, dinner, friends, hanging, music, relaxing, playing

#typical_friday  47221 non-null  object 
# 30  my_secret       47221 non-null  object 
# 31  message_if

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47221 entries, 0 to 47220
Data columns (total 30 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   bar       47221 non-null  int64
 1   dancing   47221 non-null  int64
 2   dinner    47221 non-null  int64
 3   doing     47221 non-null  int64
 4   drinks    47221 non-null  int64
 5   friday    47221 non-null  int64
 6   friends   47221 non-null  int64
 7   going     47221 non-null  int64
 8   good      47221 non-null  int64
 9   hanging   47221 non-null  int64
 10  having    47221 non-null  int64
 11  home      47221 non-null  int64
 12  just      47221 non-null  int64
 13  like      47221 non-null  int64
 14  movie     47221 non-null  int64
 15  movies    47221 non-null  int64
 16  music     47221 non-null  int64
 17  new       47221 non-null  int64
 18  night     47221 non-null  int64
 19  playing   47221 non-null  int64
 20  relaxing  47221 non-null  int64
 21  say       47221 non-null  int64
 22  time      47221 non-null  int64
 23  typical   47221 non-null  int64
 24  usually   47221 non-null  int64
 25  watching  47221 non-null  int64
 26  week      47221 non-null  int64
 27  wine      47221 non-null  int64
 28  work      47221 non-null  int64
 29  working   47221 non-null  int64
dtypes: int64(30)
memory usage: 10.8 MB

# my secret

In [49]:
#my_highlights

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

# Initialize the CountVectorizer
vectorizer = CountVectorizer(stop_words='english', max_features=40)

# Fit and transform the 'about_me' column
X = vectorizer.fit_transform(df['my_secret'])

# Convert the result to a DataFrame
sekeywords_df = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
sekeywords_df.info()

# open, think, private, love, people, admit, ask , tell, love, want

#typical_friday  47221 non-null  object 
# 30  my_secret       47221 non-null  object 
# 31  message_if

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47221 entries, 0 to 47220
Data columns (total 40 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   actually  47221 non-null  int64
 1   admit     47221 non-null  int64
 2   ask       47221 non-null  int64
 3   book      47221 non-null  int64
 4   dating    47221 non-null  int64
 5   don       47221 non-null  int64
 6   feel      47221 non-null  int64
 7   friends   47221 non-null  int64
 8   going     47221 non-null  int64
 9   good      47221 non-null  int64
 10  got       47221 non-null  int64
 11  just      47221 non-null  int64
 12  know      47221 non-null  int64
 13  life      47221 non-null  int64
 14  like      47221 non-null  int64
 15  little    47221 non-null  int64
 16  ll        47221 non-null  int64
 17  lot       47221 non-null  int64
 18  love      47221 non-null  int64
 19  make      47221 non-null  int64
 20  open      47221 non-null  int64
 21  people    47221 non-null  int64
 22  person    47221 non-null  int64
 23  pretty    47221 non-null  int64
 24  private   47221 non-null  int64
 25  probably  47221 non-null  int64
 26  profile   47221 non-null  int64
 27  really    47221 non-null  int64
 28  right     47221 non-null  int64
 29  say       47221 non-null  int64
 30  tell      47221 non-null  int64
 31  thing     47221 non-null  int64
 32  things    47221 non-null  int64
 33  think     47221 non-null  int64
 34  time      47221 non-null  int64
 35  ve        47221 non-null  int64
 36  want      47221 non-null  int64
 37  way       47221 non-null  int64
 38  willing   47221 non-null  int64
 39  years     47221 non-null  int64
dtypes: int64(40)
memory usage: 14.4 MB

# message_if

In [54]:
#my_highlights

import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer

# Initialize the CountVectorizer
vectorizer = CountVectorizer(stop_words='english', max_features=40)

# Fit and transform the 'about_me' column
X = vectorizer.fit_transform(df['message_if'])

# Convert the result to a DataFrame
sekeywords_df = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
sekeywords_df.info()

# love, fun, people, meet, enjoy, humor, friends, meet, talk, love

#typical_friday  47221 non-null  object 
# 30  my_secret       47221 non-null  object 
# 31  message_if

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47221 entries, 0 to 47220
Data columns (total 40 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   conversation  47221 non-null  int64
 1   don           47221 non-null  int64
 2   enjoy         47221 non-null  int64
 3   feel          47221 non-null  int64
 4   friends       47221 non-null  int64
 5   fun           47221 non-null  int64
 6   going         47221 non-null  int64
 7   good          47221 non-null  int64
 8   great         47221 non-null  int64
 9   guy           47221 non-null  int64
 10  humor         47221 non-null  int64
 11  interested    47221 non-null  int64
 12  interesting   47221 non-null  int64
 13  just          47221 non-null  int64
 14  kind          47221 non-null  int64
 15  know          47221 non-null  int64
 16  laugh         47221 non-null  int64
 17  life          47221 non-null  int64
 18  like          47221 non-null  int64
 19  looking       47221 non-null  int64
 20  love          47221 non-null  int64
 21  make          47221 non-null  int64
 22  meet          47221 non-null  int64
 23  message       47221 non-null  int64
 24  new           47221 non-null  int64
 25  open          47221 non-null  int64
 26  people        47221 non-null  int64
 27  person        47221 non-null  int64
 28  profile       47221 non-null  int64
 29  read          47221 non-null  int64
 30  really        47221 non-null  int64
 31  relationship  47221 non-null  int64
 32  say           47221 non-null  int64
 33  sense         47221 non-null  int64
 34  talk          47221 non-null  int64
 35  things        47221 non-null  int64
 36  think         47221 non-null  int64
 37  time          47221 non-null  int64
 38  ve            47221 non-null  int64
 39  want          47221 non-null  int64
dtypes: int64(40)
memory usage: 14.4 MB

In [103]:
# after analizing the 10 columns im creating 20 binary columns that summarize 
# relevant aspects for each profile
import pandas as pd
import re

# Manually defined keywords
keywords = ['love', 'fun', 'cooking', 'music', 'read', 'friends', 'work', 'travel', 'humor', 'movie', 'laugh', 'new', 'personality','future','people', 'smile','talk','life','tv','play']
# Columns to check
columns_to_check = ['about_me', 'my_goals', 'my_talent', 'my_highlights', 'my_favorites' , 'my_needs', 'think_about','typical_friday', 'my_secret', 'message_if']  

# Function to create binary columns
def keyword_presence(text, keyword):
    pattern = re.compile(r'\b' + re.escape(keyword) + r'\w*\b', re.IGNORECASE)
    return 1 if pattern.search(text) else 0

# Create binary columns for each keyword
for keyword in keywords:
    df[keyword] = df[columns_to_check].apply(lambda row: any(keyword_presence(str(cell), keyword) for cell in row), axis=1)

# Display the resulting DataFrame
print(df)

#travel, family, friends, fun, passionate, laugh, work, love, enjoy, new
#life, work, school, work, new, people, job, friends, people, time
#life, people, love, cooking, friends, laugh, playing, fun, dancing, listening
# hair, humor, eyes, laugh, smile, tall, personality, people, pretty, height
# books, music, movie, shows, tv, eat, food, read, life, family
# books, music, internet, coffee, friends , laughter, phone, family, love, food
# friends, future, work, love, people, time, travel, world, music, family
# movie, work, bar, dancing, dinner, friends, hanging, music, relaxing, playing
# open, think, private, love, people, admit, ask , tell, love, want
# love, fun, people, meet, enjoy, humor, friends, meet, talk, love

       profile_id  age  status sex orientation body_type            diet  \
0            1000   22  single   m    straight     curvy        anything
1            1001   35  single   m    straight   average           other
2            1002   23  single   m    straight    skinny      vegetarian
3            1003   29  single   m    straight       fit  rather not say
4            1004   29  single   m    straight   average        anything
...           ...  ...     ...  ..         ...       ...             ...
47145       48216   32  single   m    bisexual    skinny        anything
47146       48217   24  single   m    straight       fit        anything
47147       48218   42  single   m    straight   average        anything
47148       48219   27  single   m    straight       fit        anything
47149       48220   39  single   m         gay   average  rather not say

          drinks           drugs        education  ...  laugh    new  \
0      sometimes           never  College or more  ...   True   True
1          often       sometimes  College or more  ...  False   True
2      sometimes  rather not say  College or more  ...  False  False
3      sometimes           never  College or more  ...  False   True
4      sometimes  rather not say  College or more  ...   True   True
...          ...             ...              ...  ...    ...    ...
47145  sometimes  rather not say  College or more  ...  False  False
47146      often       sometimes  College or more  ...  False   True
47147      never           never  College or more  ...  False   True
47148  sometimes           often  College or more  ...  False  False
47149  sometimes  rather not say  College or more  ...   True   True

       personality future people  smile   talk   life     tv   play
0            False  False   True   True   True   True  False  False
1            False  False   True  False  False   True   True   True
2            False  False   True  False  False  False  False   True
3            False  False  False   True  False   True   True   True
4            False  False   True   True  False  False   True   True
...            ...    ...    ...    ...    ...    ...    ...    ...
47145        False  False   True  False  False  False  False  False
47146        False  False  False  False  False  False   True  False
47147        False  False  False  False  False   True  False  False
47148        False  False   True   True  False   True  False  False
47149        False  False   True  False   True  False  False  False

[47150 rows x 53 columns]

In [104]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47150 entries, 0 to 47149
Data columns (total 53 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   profile_id       47150 non-null  int64
 1   age              47150 non-null  int64
 2   status           47150 non-null  object
 3   sex              47150 non-null  object
 4   orientation      47150 non-null  object
 5   body_type        47150 non-null  object
 6   diet             47150 non-null  object
 7   drinks           47150 non-null  object
 8   drugs            47150 non-null  object
 9   education        47150 non-null  object
 10  ethnicity        47150 non-null  object
 11  height           47150 non-null  float64
 12  income           47150 non-null  int64
 13  job              47150 non-null  object
 14  last_online      47150 non-null  object
 15  offspring        47150 non-null  object
 16  pets             47150 non-null  object
 17  religion         47150 non-null  object
 18  sign             47150 non-null  object
 19  smokes           47150 non-null  object
 20  speaks           47150 non-null  int64
 21  about_me         47150 non-null  object
 22  my_goals         47150 non-null  object
 23  my_talent        47150 non-null  object
 24  my_highlights    47150 non-null  object
 25  my_favorites     47150 non-null  object
 26  my_needs         47150 non-null  object
 27  think_about      47150 non-null  object
 28  typical_friday   47150 non-null  object
 29  my_secret        47150 non-null  object
 30  message_if       47150 non-null  object
 31  city             47150 non-null  object
 32  ethnicity_count  47150 non-null  int64
 33  love             47150 non-null  bool
 34  fun              47150 non-null  bool
 35  cooking          47150 non-null  bool
 36  music            47150 non-null  bool
 37  read             47150 non-null  bool
 38  friends          47150 non-null  bool
 39  work             47150 non-null  bool
 40  travel           47150 non-null  bool
 41  humor            47150 non-null  bool
 42  movie            47150 non-null  bool
 43  laugh            47150 non-null  bool
 44  new              47150 non-null  bool
 45  personality      47150 non-null  bool
 46  future           47150 non-null  bool
 47  people           47150 non-null  bool
 48  smile            47150 non-null  bool
 49  talk             47150 non-null  bool
 50  life             47150 non-null  bool
 51  tv               47150 non-null  bool
 52  play             47150 non-null  bool
dtypes: bool(20), float64(1), int64(5), object(27)
memory usage: 12.8+ MB

In [ ]:
# export a df without the essay column but the 20 nw binary ones

In [105]:
df2=df.copy()

# drop all the essay columns

In [106]:
df2.drop(columns=['about_me','my_goals','my_talent','my_highlights','my_favorites','my_needs','think_about','typical_friday','my_secret','message_if'], inplace=True)

In [107]:
df3=df2.copy()

In [108]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47150 entries, 0 to 47149
Data columns (total 43 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   profile_id       47150 non-null  int64
 1   age              47150 non-null  int64
 2   status           47150 non-null  object
 3   sex              47150 non-null  object
 4   orientation      47150 non-null  object
 5   body_type        47150 non-null  object
 6   diet             47150 non-null  object
 7   drinks           47150 non-null  object
 8   drugs            47150 non-null  object
 9   education        47150 non-null  object
 10  ethnicity        47150 non-null  object
 11  height           47150 non-null  float64
 12  income           47150 non-null  int64
 13  job              47150 non-null  object
 14  last_online      47150 non-null  object
 15  offspring        47150 non-null  object
 16  pets             47150 non-null  object
 17  religion         47150 non-null  object
 18  sign             47150 non-null  object
 19  smokes           47150 non-null  object
 20  speaks           47150 non-null  int64
 21  city             47150 non-null  object
 22  ethnicity_count  47150 non-null  int64
 23  love             47150 non-null  bool
 24  fun              47150 non-null  bool
 25  cooking          47150 non-null  bool
 26  music            47150 non-null  bool
 27  read             47150 non-null  bool
 28  friends          47150 non-null  bool
 29  work             47150 non-null  bool
 30  travel           47150 non-null  bool
 31  humor            47150 non-null  bool
 32  movie            47150 non-null  bool
 33  laugh            47150 non-null  bool
 34  new              47150 non-null  bool
 35  personality      47150 non-null  bool
 36  future           47150 non-null  bool
 37  people           47150 non-null  bool
 38  smile            47150 non-null  bool
 39  talk             47150 non-null  bool
 40  life             47150 non-null  bool
 41  tv               47150 non-null  bool
 42  play             47150 non-null  bool
dtypes: bool(20), float64(1), int64(5), object(17)
memory usage: 9.2+ MB

In [94]:
# Count 'rather not say' values in each column
rather_not_say_counts = df3.apply(lambda x: (x == 'rather not say').sum())

print(rather_not_say_counts)

profile_id             0
age                    0
status                 0
sex                    0
orientation            0
body_type              0
diet               16689
drinks              1281
drugs              10432
education           3149
ethnicity           3319
height                 0
income                 0
job                    0
last_online            0
offspring          32512
pets               13610
religion               0
sign                   0
smokes              3051
speaks                 0
city                   0
ethnicity_count        0
dtype: int64

In [109]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47150 entries, 0 to 47149
Data columns (total 43 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   profile_id       47150 non-null  int64
 1   age              47150 non-null  int64
 2   status           47150 non-null  object
 3   sex              47150 non-null  object
 4   orientation      47150 non-null  object
 5   body_type        47150 non-null  object
 6   diet             47150 non-null  object
 7   drinks           47150 non-null  object
 8   drugs            47150 non-null  object
 9   education        47150 non-null  object
 10  ethnicity        47150 non-null  object
 11  height           47150 non-null  float64
 12  income           47150 non-null  int64
 13  job              47150 non-null  object
 14  last_online      47150 non-null  object
 15  offspring        47150 non-null  object
 16  pets             47150 non-null  object
 17  religion         47150 non-null  object
 18  sign             47150 non-null  object
 19  smokes           47150 non-null  object
 20  speaks           47150 non-null  int64
 21  city             47150 non-null  object
 22  ethnicity_count  47150 non-null  int64
 23  love             47150 non-null  bool
 24  fun              47150 non-null  bool
 25  cooking          47150 non-null  bool
 26  music            47150 non-null  bool
 27  read             47150 non-null  bool
 28  friends          47150 non-null  bool
 29  work             47150 non-null  bool
 30  travel           47150 non-null  bool
 31  humor            47150 non-null  bool
 32  movie            47150 non-null  bool
 33  laugh            47150 non-null  bool
 34  new              47150 non-null  bool
 35  personality      47150 non-null  bool
 36  future           47150 non-null  bool
 37  people           47150 non-null  bool
 38  smile            47150 non-null  bool
 39  talk             47150 non-null  bool
 40  life             47150 non-null  bool
 41  tv               47150 non-null  bool
 42  play             47150 non-null  bool
dtypes: bool(20), float64(1), int64(5), object(17)
memory usage: 9.2+ MB

In [97]:
okcupid_essaynormalized = df3

# Specify the folder path
folder_path = ('/Users/marina/Desktop/final_project/data/cleaned/')

# Specify the file name
file_name = 'okcupid_essaynormalized.csv'

 #Combine the folder path and file name
file_path = os.path.join(folder_path, file_name)

# Export the DataFrame to a CSV file
okcupid_essaynormalized.to_csv(file_path, index=False)

print(f'DataFrame exported to {file_path}')

DataFrame exported to /Users/marina/Desktop/final_project/data/cleaned/okcupid_essaynormalized.csv

# Create raw df for sql by table

In [113]:
# Create new DataFrames based on specified columns
profile_preferences = df3[['profile_id', 'orientation', 'religion', 'pets', 'offspring']]
profile_main = df3[['profile_id', 'age', 'status', 'orientation', 'body_type', 'sex', 'ethnicity', 'height', 'sign']]
profile_location = df3[['profile_id', 'city']]
profile_lastonline = df3[['profile_id', 'last_online']]
profile_habits = df3[['profile_id', 'diet', 'drinks', 'drugs', 'smokes']]
profile_qualifications = df3[['profile_id', 'job', 'education', 'speaks', 'income']]
profile_whatmatters = df3[['profile_id', 'love', 'fun', 'cooking', 'music', 'read', 'friends', 'work', 'travel', 'humor', 'movie', 'laugh', 'new', 'personality', 'future', 'people', 'smile', 'talk', 'life', 'tv', 'play']]

# Optional: Save the new DataFrames to CSV files
profile_preferences.to_csv('profile_preferences.csv', index=False)
profile_main.to_csv('profile_main.csv', index=False)
profile_location.to_csv('profile_location.csv', index=False)
profile_lastonline.to_csv('profile_lastonline.csv', index=False)
profile_habits.to_csv('profile_habits.csv', index=False)
profile_qualifications.to_csv('profile_qualifications.csv', index=False)
profile_whatmatters.to_csv('profile_whatmatters.csv', index=False)

In [115]:
# List of DataFrames and corresponding file names
dataframes = [
    profile_preferences,
    profile_main,
    profile_location,
    profile_lastonline,
    profile_habits,
    profile_qualifications,
    profile_whatmatters
]

file_names = [
    'profile_preferences.csv',
    'profile_main.csv',
    'profile_location.csv',
    'profile_lastonline.csv',
    'profile_habits.csv',
    'profile_qualifications.csv',
    'profile_whatmatters.csv'
]

# Specify the folder path
folder_path = '/Users/marina/Desktop/final_project/data/sql/raw'

# Save DataFrames to CSV files
for df, file_name in zip(dataframes, file_names):
    file_path = os.path.join(folder_path, file_name)
    df.to_csv(file_path, index=False)
    print(f'DataFrame exported to {file_path}')

DataFrame exported to /Users/marina/Desktop/final_project/data/sql/raw/profile_preferences.csv
DataFrame exported to /Users/marina/Desktop/final_project/data/sql/raw/profile_main.csv
DataFrame exported to /Users/marina/Desktop/final_project/data/sql/raw/profile_location.csv
DataFrame exported to /Users/marina/Desktop/final_project/data/sql/raw/profile_lastonline.csv
DataFrame exported to /Users/marina/Desktop/final_project/data/sql/raw/profile_habits.csv
DataFrame exported to /Users/marina/Desktop/final_project/data/sql/raw/profile_qualifications.csv
DataFrame exported to /Users/marina/Desktop/final_project/data/sql/raw/profile_whatmatters.csv

In [ ]:
#/Users/marina/Desktop/final_project/data/sql/raw